### ISSUE TITLE
event details cleanup

### ISSUE THREAD

**Issue by jgravois** [esridc/hub-components#13]
- [ ] swap in a cityx sample event
- [ ] pull OAuth calls out into a shared utility function
- [ ] choose a more neutral font
- [ ] add instructions for creating a community account to the demo page
- [ ] advertise browser support more clearly

**Comment by tomwayson** [comment]
also components should use an existing session, for example if there are 2 event components on the same page and a user wants to register for both, they should only have log in once.

We could extend this idea to include the notion of storing the session in a cookie so that a user remains logged in on return visits.
